columns:
    id:
        label: Id
        name: id
        type: integer
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    course:
        label: Course
        name: course
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    title:
        label: Title
        name: title
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    is_active:
        label: 'Is active'
        name: is_active
        type: boolean
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
actions:
    is_active:
        route:   admin_lessons_publish
        extends: publish
    new:
        route: admin_lessons_new
        extends: new
    edit:
        route: admin_lessons_edit
        extends: edit
    delete:
        route: admin_lessons_delete
        extends: delete
        
templates:
    form:
        edit: SmirikCourseBundle:Admin/Lesson:edit.html.twig
        new: SmirikCourseBundle:Admin/Lesson:new.html.twig
