columns:
    id:
        label: Id
        name: id
        type: integer
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    lesson:
        label: Lesson
        name: lesson
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    task:
        label: Task
        name: task
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    user:
        label: User
        name: name
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    text:
        label: Text
        name: text
        type: text
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    url:
        label: Url
        name: url
        type: string
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    file:
        label: File
        name: file
        type: string
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    status:
        label: Status
        name: status
        type: integer
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
        templates:
            filter: SmirikCourseBundle:Admin/Filter:status.html.twig
            list: SmirikCourseBundle:Admin/Column:status.html.twig
    mark:
        label: Mark
        name: mark
        type: integer
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
actions:
    accept:
        label:   Process
        name:    process
        builder: chain
        route:   admin_users_tasks_accept
        options:
            route_with_id: true
            confirmation: false
        getter:  getStatus
        setter:  setStatus
        data:
            - { key: 0, text: 'In progress' }
            - { key: 1, text: 'Pending' }
            - { key: 2, text: 'Rejected' }
            - { key: 3, text: 'Accepted' }
            - { key: 4, text: 'Failed' }
            - { key: default, text: 'Reject' }
        template:
            list: SmirikCourseBundle:Admin/Action:process.html.twig
    new:
        route: admin_users_tasks_new
        extends: new
    delete:
        route: admin_users_tasks_delete
        extends: delete
