columns:
    id:
        label: Id
        name: id
        type: integer
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    title:
        label: Title
        name: title
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    description:
        label: Description
        name: description
        type: text
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    type:
        label: Type
        name: type
        type: boolean
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    file:
        extends: file
        type: image
        builder: file
        options:
            listable:   true
            editable:   true
            sortable:   false
            filterable: false
            upload_path: /uploads/courses/
            randomize_name: true
    is_public:
        label: 'Is public'
        name: is_public
        type: boolean
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    is_active:
        label: 'Is active'
        name: is_active
        type: boolean
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
actions:
    is_active:
        route:   admin_courses_publish
        extends: publish
    new:
        route: admin_courses_new
        extends: new
    edit:
        route: admin_courses_edit
        extends: edit
    delete:
        route: admin_courses_delete
        extends: delete
