services:
    course.manager:
        class: Smirik\CourseBundle\Manager\CourseManager
        calls:
            - [ setManagers, [ "@lesson.manager", "@user_quiz.manager", "@user_task.manager" ] ]
    question.manager:
        class: Smirik\CourseBundle\Manager\QuestionManager
    lesson.manager:
        class: Smirik\CourseBundle\Manager\LessonManager
    task.manager:
        class: Smirik\CourseBundle\Manager\TaskManager
    user_task.manager:
        class: Smirik\CourseBundle\Manager\UserTaskManager
    user_lesson.manager:
        class: Smirik\CourseBundle\Manager\UserLessonManager
        calls:
            - [ setManagers, [ "@user_task.manager" ] ]

    courses.configure_menu_listener:
        class: Smirik\CourseBundle\Listener\ConfigureMenuListener
        arguments: ["@security.context"]
        tags:
            - { name: kernel.event_listener, event: admin.menu_configure, method: onMenuConfigure }
            - { name: kernel.event_listener, event: main.menu_configure, method: onMainMenuConfigure }
    smirik.course.twig.extension:
        class: Smirik\CourseBundle\Twig\Extension\CourseExtension
        calls:
            - [ setCourseManager, ["@course.manager"] ]
            - [ setContext,       ["@security.context"] ]
        tags:
            - { name: twig.extension }
