services:
  course.manager:
    class: Smirik\CourseBundle\Manager\CourseManager
    
  courses.configure_menu_listener:
      class: Smirik\CourseBundle\Listener\ConfigureMenuListener
      arguments: ["@security.context"]
      tags:
        - { name: kernel.event_listener, event: admin.menu_configure, method: onMenuConfigure }
        - { name: kernel.event_listener, event: main.menu_configure, method: onMainMenuConfigure }
          